Repository Adyen/adyen-android, pull requests merged in 2023-08, with the labels that each got.

#1283 Allow CVC to be empty when bin lookup returns "hidden"
  card/src/main/java/com/adyen/checkout/card/internal/data/model/Brand.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/StoredCardDelegate.kt
  card/src/main/java/com/adyen/checkout/card/internal/util/CardValidationUtils.kt
  card/src/test/java/com/adyen/checkout/card/internal/util/CardValidationUtilsTest.kt
Labels: Fix

#1281 Add on redirect callback
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/Adyen3DS2Delegate.kt
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
  action-core/src/main/java/com/adyen/checkout/action/core/internal/ActionHandlingComponent.kt
  action-core/src/main/java/com/adyen/checkout/action/core/internal/DefaultActionHandlingComponent.kt
  action-core/src/main/java/com/adyen/checkout/action/core/internal/ui/DefaultGenericActionDelegate.kt
  action-core/src/main/java/com/adyen/checkout/action/core/internal/ui/GenericActionDelegate.kt
  action-core/src/test/java/com/adyen/checkout/action/core/TestActionDelegate.kt
  components-core/src/main/java/com/adyen/checkout/components/core/RedirectableActionComponent.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/RedirectableDelegate.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/BaseDropInServiceContract.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/provider/ComponentParsingProvider.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/service/BaseDropInService.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/service/BaseDropInServiceInterfaces.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/ActionComponentDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/BaseComponentDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInBottomSheetDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/GiftCardComponentDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/GooglePayComponentDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PaymentMethodListDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PreselectedStoredPaymentMethodFragment.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/CardActivity.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardActivity.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardTakenOverActivity.kt
  qr-code/src/main/java/com/adyen/checkout/qrcode/QRCodeComponent.kt
  qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/DefaultQRCodeDelegate.kt
  qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/QRCodeDelegate.kt
  redirect/src/main/java/com/adyen/checkout/redirect/RedirectComponent.kt
  redirect/src/main/java/com/adyen/checkout/redirect/internal/ui/DefaultRedirectDelegate.kt
  redirect/src/main/java/com/adyen/checkout/redirect/internal/ui/RedirectDelegate.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/DefaultRedirectHandler.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/RedirectHandler.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/test/TestRedirectHandler.kt
Labels: Feature

#1284 Allow CVC to be empty when bin lookup returns "hidden" (v4)
  card/src/main/java/com/adyen/checkout/card/CardComponent.kt
  card/src/main/java/com/adyen/checkout/card/api/model/Brand.kt
  card/src/main/java/com/adyen/checkout/card/util/CardValidationUtils.kt
Labels: Fix

#1287 On bin changed callback
  card/src/main/java/com/adyen/checkout/card/CardComponent.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/CardDelegate.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/StoredCardDelegate.kt
  card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/BaseDropInServiceContract.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/service/BaseDropInService.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/service/BaseDropInServiceInterfaces.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/CardComponentDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInBottomSheetDialogFragment.kt
  example-app/src/main/java/com/adyen/checkout/example/extensions/LogExtensions.kt
  example-app/src/main/java/com/adyen/checkout/example/service/ExampleAdvancedDropInService.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/CardActivity.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/DefaultRedirectHandler.kt
Labels: Feature

#1296 Propagate details on error, cancel and timeout from 3ds2 sdk (v4)
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Serializer.kt
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/model/ChallengeResult.kt
  build.gradle
  config/gradle/checksums.gradle
Labels: Feature

#1292 Propagate details on error, cancel and timeout from 3ds2 sdk
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/data/model/Adyen3DS2Serializer.kt
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/data/model/ChallengeResult.kt
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
  3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
  card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
  card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
  dependencies.gradle
  gradle/verification-metadata.xml
Labels: Feature

#1298 Add event to navigate to the payment methods list
  drop-in/src/main/java/com/adyen/checkout/dropin/DropInServiceResult.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInViewModel.kt
Labels: Feature

#1306 Upgrade to target sdk 33 (v4)
  build.gradle
  card/src/main/java/com/adyen/checkout/card/AddressConfiguration.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/DropInViewModelFactory.kt
  gradle/wrapper/gradle-wrapper.properties
  ui-core/src/main/java/com/adyen/checkout/components/ui/view/AdyenSwipeToRevealLayout.kt
Labels: Feature, Dependencies

#1305 Fix dual branded flow check
  card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
Labels: Fix

#1304 Fix QR code actions for InstantPaymentComponent
  instant/src/main/java/com/adyen/checkout/instant/InstantPaymentComponent.kt
Labels: Fix

#1308 Android 14 support
  .github/workflows/update_verification_metadata.yml
  dependencies.gradle
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/BaseComponentDialogFragment.kt
  gradle/verification-metadata.xml
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/AdyenSwipeToRevealLayout.kt
Labels: Feature, Dependencies

#1319 Fix dual branded flow check (v4)
  card/src/main/java/com/adyen/checkout/card/CardComponent.kt
Labels: Fix

#1325 Fix address fetch crash (v4)
  card/src/main/java/com/adyen/checkout/card/AddressDelegate.kt
  card/src/main/java/com/adyen/checkout/card/CardComponent.kt
  card/src/main/java/com/adyen/checkout/card/ui/AddressSpecification.kt
Labels: Fix
