Repository Adyen/adyen-android, pull requests merged in 2024-04, with the labels that each got.

#1534 Add missing styles for card
  RELEASE_NOTES.md
  card/src/main/res/values/styles.xml
Labels: Fix

#1552 Fix InflateException
  RELEASE_NOTES.md
  card/src/main/res/values/styles.xml
  ui-core/src/main/res/values/styles.xml
Labels: Fix

#1553 Fix existing string resources with multiple substitutions
  RELEASE_NOTES.md
  card/src/main/res/values-ar/strings.xml
  card/src/main/res/values-cs-rCZ/strings.xml
  card/src/main/res/values-da-rDK/strings.xml
  card/src/main/res/values-de-rDE/strings.xml
  card/src/main/res/values-el-rGR/strings.xml
  card/src/main/res/values-es-rES/strings.xml
  card/src/main/res/values-fi-rFI/strings.xml
  card/src/main/res/values-fr-rFR/strings.xml
  card/src/main/res/values-hr-rHR/strings.xml
  card/src/main/res/values-hu-rHU/strings.xml
  card/src/main/res/values-it-rIT/strings.xml
  card/src/main/res/values-ja-rJP/strings.xml
  card/src/main/res/values-ko-rKR/strings.xml
  card/src/main/res/values-nb-rNO/strings.xml
  card/src/main/res/values-nl-rNL/strings.xml
  card/src/main/res/values-pl-rPL/strings.xml
  card/src/main/res/values-pt-rBR/strings.xml
  card/src/main/res/values-pt-rPT/strings.xml
  card/src/main/res/values-ro-rRO/strings.xml
  card/src/main/res/values-ru-rRU/strings.xml
  card/src/main/res/values-sk-rSK/strings.xml
  card/src/main/res/values-sl-rSI/strings.xml
  card/src/main/res/values-sv-rSE/strings.xml
  card/src/main/res/values-zh-rCN/strings.xml
  card/src/main/res/values-zh-rTW/strings.xml
  card/src/main/res/values/strings.xml
Labels: Fix

#1549 Fix onAdditionalDetails being called multiple times
  RELEASE_NOTES.md
  components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/StatusRepository.kt
  components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/DefaultStatusRepositoryTest.kt
  test-core/src/main/java/com/adyen/checkout/test/extensions/TestFlow.kt
Labels: Fix

#1559 Address memory leaks
  RELEASE_NOTES.md
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/service/BaseDropInService.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/CardComponentDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInBottomSheetDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PaymentMethodListDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PreselectedStoredPaymentMethodFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/util/DropInExt.kt
  test-core/src/main/java/com/adyen/checkout/test/extensions/ViewModelExtensions.kt
Labels: Fix

#1579 Fix memroy leak in action components
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/provider/Adyen3DS2ComponentProvider.kt
  RELEASE_NOTES.md
  action-core/src/main/java/com/adyen/checkout/action/core/internal/provider/GenericActionComponentProvider.kt
  await/src/main/java/com/adyen/checkout/await/internal/provider/AwaitComponentProvider.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/ActionComponentEventHandler.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/DefaultActionComponentEventHandler.kt
  qr-code/src/main/java/com/adyen/checkout/qrcode/internal/provider/QRCodeComponentProvider.kt
  redirect/src/main/java/com/adyen/checkout/redirect/internal/provider/RedirectComponentProvider.kt
  voucher/src/main/java/com/adyen/checkout/voucher/internal/provider/VoucherComponentProvider.kt
  wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/provider/WeChatPayActionComponentProvider.kt
Labels: Fix

#1581 UI neutrality
  RELEASE_NOTES.md
  components-core/src/main/java/com/adyen/checkout/components/core/internal/util/CountryUtils.kt
  components-core/src/test/java/com/adyen/checkout/components/core/internal/util/CountryUtilsTest.kt
  econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/view/EContextView.kt
  example-app/src/main/res/values/strings.xml
  mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/view/MbWayView.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/CountryViewHolder.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/model/CountryModel.kt
  ui-core/src/main/res/layout/country_view.xml
  ui-core/src/main/res/values-ar/strings.xml
  ui-core/src/main/res/values-cs-rCZ/strings.xml
  ui-core/src/main/res/values-da-rDK/strings.xml
  ui-core/src/main/res/values-de-rDE/strings.xml
  ui-core/src/main/res/values-el-rGR/strings.xml
  ui-core/src/main/res/values-es-rES/strings.xml
  ui-core/src/main/res/values-fi-rFI/strings.xml
  ui-core/src/main/res/values-fr-rFR/strings.xml
  ui-core/src/main/res/values-hr-rHR/strings.xml
  ui-core/src/main/res/values-hu-rHU/strings.xml
  ui-core/src/main/res/values-it-rIT/strings.xml
  ui-core/src/main/res/values-ja-rJP/strings.xml
  ui-core/src/main/res/values-ko-rKR/strings.xml
  ui-core/src/main/res/values-nb-rNO/strings.xml
  ui-core/src/main/res/values-nl-rNL/strings.xml
  ui-core/src/main/res/values-pl-rPL/strings.xml
  ui-core/src/main/res/values-pt-rBR/strings.xml
  ui-core/src/main/res/values-pt-rPT/strings.xml
  ui-core/src/main/res/values-ro-rRO/strings.xml
  ui-core/src/main/res/values-ru-rRU/strings.xml
  ui-core/src/main/res/values-sk-rSK/strings.xml
  ui-core/src/main/res/values-sl-rSI/strings.xml
  ui-core/src/main/res/values-sv-rSE/strings.xml
  ui-core/src/main/res/values-zh-rTW/strings.xml
  ui-core/src/main/res/values/strings.xml
Labels: Feature

#1584 Fix initial log level
  RELEASE_NOTES.md
  checkout-core/src/main/java/com/adyen/checkout/core/AdyenLogger.kt
  checkout-core/src/test/java/com/adyen/checkout/core/internal/util/AdyenLoggerTest.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/DropIn.kt
Labels: Fix

#1585 Update 3ds2 sdk
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/data/model/Adyen3DS2Serializer.kt
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/data/model/ChallengeResult.kt
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/provider/Adyen3DS2ComponentProvider.kt
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
  3ds2/src/test/java/com/adyen/checkout/adyen3ds2/Adyen3DS2ComponentTest.kt
  3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
  action-core/src/test/java/com/adyen/threeds2/ThreeDS2Service.kt
  card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
  card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
  card/src/test/java/com/adyen/threeds2/ThreeDS2Service.java
  components-core/src/main/java/com/adyen/checkout/components/core/internal/util/Base64Encoder.kt
  dependencies.gradle
  gradle/verification-metadata.xml
Labels: Dependencies

#1589 Display validation error on CardView when no address has been selected
  RELEASE_NOTES.md
  card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardView.kt
  card/src/main/res/values/styles.xml
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/model/AddressOutputData.kt
  ui-core/src/main/res/template/values/strings.xml.tt
  ui-core/src/main/res/values-ar/strings.xml
  ui-core/src/main/res/values-cs-rCZ/strings.xml
  ui-core/src/main/res/values-da-rDK/strings.xml
  ui-core/src/main/res/values-de-rDE/strings.xml
  ui-core/src/main/res/values-el-rGR/strings.xml
  ui-core/src/main/res/values-es-rES/strings.xml
  ui-core/src/main/res/values-fi-rFI/strings.xml
  ui-core/src/main/res/values-fr-rFR/strings.xml
  ui-core/src/main/res/values-hr-rHR/strings.xml
  ui-core/src/main/res/values-hu-rHU/strings.xml
  ui-core/src/main/res/values-it-rIT/strings.xml
  ui-core/src/main/res/values-ja-rJP/strings.xml
  ui-core/src/main/res/values-ko-rKR/strings.xml
  ui-core/src/main/res/values-nb-rNO/strings.xml
  ui-core/src/main/res/values-nl-rNL/strings.xml
  ui-core/src/main/res/values-pl-rPL/strings.xml
  ui-core/src/main/res/values-pt-rBR/strings.xml
  ui-core/src/main/res/values-pt-rPT/strings.xml
  ui-core/src/main/res/values-ro-rRO/strings.xml
  ui-core/src/main/res/values-ru-rRU/strings.xml
  ui-core/src/main/res/values-sk-rSK/strings.xml
  ui-core/src/main/res/values-sl-rSI/strings.xml
  ui-core/src/main/res/values-sv-rSE/strings.xml
  ui-core/src/main/res/values-zh-rCN/strings.xml
  ui-core/src/main/res/values-zh-rTW/strings.xml
  ui-core/src/main/res/values/strings.xml
Labels: Fix

#1586 Remove opened triggers from the release notes check action
  .github/pull_request_template.md
  .github/workflows/check_labels.yml
  .github/workflows/check_release_notes.yml
Labels: Chore

#1576 Reduce release age to 14 days
  renovate.json
Labels: Dependencies
