Repository Adyen/adyen-android, pull requests merged in 2024-05, with the labels that each got.

#1561 Setup UI testing
  .github/workflows/assemble.yml
  .github/workflows/check_develop.yml
  .github/workflows/check_release.yml
  .github/workflows/code_analysis.yml
  .github/workflows/generate_dependency_graph.yml
  .github/workflows/publish_docs.yml
  .github/workflows/publish_release.yml
  .github/workflows/run_tests.yml
  .github/workflows/run_ui_tests.yml
  .github/workflows/sonar_cloud.yml
  .github/workflows/update_verification_metadata.yml
  build.gradle
  dependencies.gradle
  example-app/build.gradle
  example-app/ci.local.gradle
  example-app/src/androidTest/AndroidManifest.xml
  example-app/src/androidTest/java/com/adyen/checkout/HiltTestRunner.kt
  example-app/src/androidTest/java/com/adyen/checkout/MainTest.kt
  gradle/verification-metadata.xml
Labels: Chore

#1592 Fix crash caused by obfuscation of action configurations
  RELEASE_NOTES.md
  components-core/src/main/java/com/adyen/checkout/components/core/CheckoutConfiguration.kt
Labels: Fix

#1611 Improve client key validation
  components-core/src/main/java/com/adyen/checkout/components/core/internal/BaseConfigurationBuilder.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/util/ValidationUtils.kt
  components-core/src/test/java/com/adyen/checkout/components/core/internal/util/ValidationUtilsTest.kt
Labels: Chore

#1605 Speed up sonar
  .github/workflows/assemble.yml
  .github/workflows/check_release.yml
  .github/workflows/code_analysis.yml
  .github/workflows/publish_docs.yml
  .github/workflows/publish_release.yml
  .github/workflows/run_tests.yml
  .github/workflows/run_ui_tests.yml
  .github/workflows/sonar_cloud.yml
  .github/workflows/update_verification_metadata.yml
  build.gradle
  gradle.properties
Labels: Chore

#1614 Migrate to non-transitive R classes
  ach/src/main/java/com/adyen/checkout/ach/internal/ui/view/ACHDirectDebitView.kt
  await/src/main/java/com/adyen/checkout/await/internal/ui/view/AwaitView.kt
  bacs/src/main/java/com/adyen/checkout/bacs/internal/ui/view/BacsDirectDebitConfirmationView.kt
  bacs/src/main/java/com/adyen/checkout/bacs/internal/ui/view/BacsDirectDebitInputView.kt
  blik/src/main/java/com/adyen/checkout/blik/internal/ui/view/BlikView.kt
  boleto/src/main/java/com/adyen/checkout/boleto/internal/ui/view/BoletoView.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardView.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/view/StoredCardView.kt
  cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/ui/view/CashAppPayView.kt
  cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/ui/view/CashAppPayWaitingView.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/ActionComponentDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/BacsDirectDebitDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/BaseComponentDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInBottomSheetDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/GiftCardComponentDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/GiftCardPaymentConfirmationDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PaymentMethodListDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PreselectedStoredPaymentMethodFragment.kt
  econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/view/EContextView.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/bacs/BacsViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/blik/BlikViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/GooglePayViewModel.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/view/GiftCardView.kt
  gradle.properties
  gradle/verification-metadata.xml
  mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/view/MbWayView.kt
  paybybank/src/main/java/com/adyen/checkout/paybybank/internal/ui/view/PayByBankView.kt
  qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/view/FullQRCodeView.kt
  qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/view/SimpleQRCodeView.kt
  sepa/src/main/java/com/adyen/checkout/sepa/internal/ui/view/SepaView.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/ImageSaver.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/ThemeUtil.kt
  upi/src/main/java/com/adyen/checkout/upi/internal/ui/view/UPIView.kt
  voucher/src/main/java/com/adyen/checkout/voucher/internal/ui/view/FullVoucherView.kt
  voucher/src/main/java/com/adyen/checkout/voucher/internal/ui/view/SimpleVoucherView.kt
Labels: Chore

#1612 Display pay button in components if created by drop in
  ach/src/main/java/com/adyen/checkout/ach/internal/ui/model/ACHDirectDebitComponentParamsMapper.kt
  ach/src/test/java/com/adyen/checkout/ach/internal/ui/model/ACHDirectDebitComponentParamsMapperTest.kt
  bcmc/src/main/java/com/adyen/checkout/bcmc/internal/ui/model/BcmcComponentParamsMapper.kt
  bcmc/src/test/java/com/adyen/checkout/bcmc/internal/ui/model/BcmcComponentParamsMapperTest.kt
  boleto/src/main/java/com/adyen/checkout/boleto/internal/ui/model/BoletoComponentParamsMapper.kt
  boleto/src/test/java/com/adyen/checkout/boleto/internal/ui/model/BoletoComponentParamsMapperTest.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/model/CardComponentParamsMapper.kt
  card/src/test/java/com/adyen/checkout/card/internal/ui/model/CardComponentParamsMapperTest.kt
  cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/ui/model/CashAppPayComponentParamsMapper.kt
  cashapppay/src/test/java/com/adyen/checkout/cashapppay/internal/ui/model/CashAppPayComponentParamsMapperTest.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/ButtonComponentParamsMapper.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/DropInOverrideParams.kt
  components-core/src/test/java/com/adyen/checkout/components/core/ButtonTestConfiguration.kt
  components-core/src/test/java/com/adyen/checkout/components/core/internal/ui/model/ButtonComponentParamsMapperTest.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardComponentParamsMapper.kt
  giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardComponentParamsMapperTest.kt
  issuer-list/src/main/java/com/adyen/checkout/issuerlist/internal/ui/model/IssuerListComponentParamsMapper.kt
  issuer-list/src/test/java/com/adyen/checkout/issuerlist/internal/ui/model/IssuerListComponentParamsMapperTest.kt
Labels: Chore

#1629 Fix drop-in unable to handle 3DS2 on API v66 and below
  RELEASE_NOTES.md
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/ActionComponentDialogFragment.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
Labels: Fix

#1628 Support changing the custom tabs toolbar and navigation colors
  RELEASE_NOTES.md
  docs/UI_CUSTOMIZATION.md
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/DefaultRedirectHandler.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/CustomTabsLauncher.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/PdfOpener.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/ThemeUtil.kt
  ui-core/src/main/res/values/attrs.xml
  ui-core/src/main/res/values/styles.xml
  voucher/src/main/java/com/adyen/checkout/voucher/internal/ui/view/FullVoucherView.kt
Labels: Feature

#1489 Restore action handling state
  RELEASE_NOTES.md
  action-core/src/main/java/com/adyen/checkout/action/core/internal/provider/GenericActionComponentProvider.kt
  action-core/src/main/java/com/adyen/checkout/action/core/internal/ui/DefaultGenericActionDelegate.kt
  action-core/src/test/java/com/adyen/checkout/action/core/ui/DefaultGenericActionDelegateTest.kt
  await/src/main/java/com/adyen/checkout/await/internal/provider/AwaitComponentProvider.kt
  await/src/main/java/com/adyen/checkout/await/internal/ui/DefaultAwaitDelegate.kt
  await/src/test/java/com/adyen/checkout/await/internal/ui/DefaultAwaitDelegateTest.kt
  qr-code/src/main/java/com/adyen/checkout/qrcode/internal/provider/QRCodeComponentProvider.kt
  qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/DefaultQRCodeDelegate.kt
  qr-code/src/test/java/com/adyen/checkout/qrcode/internal/ui/DefaultQRCodeDelegateTest.kt
  redirect/src/main/java/com/adyen/checkout/redirect/internal/ui/DefaultRedirectDelegate.kt
  voucher/src/main/java/com/adyen/checkout/voucher/internal/provider/VoucherComponentProvider.kt
  voucher/src/main/java/com/adyen/checkout/voucher/internal/ui/DefaultVoucherDelegate.kt
  voucher/src/test/java/com/adyen/checkout/voucher/internal/ui/DefaultVoucherDelegateTest.kt
Labels: Fix

#1632 Restore 3DS2 state after process death
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/SharedChallengeStatusHandler.kt
  3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
  3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/SharedChallengeStatusHandlerTest.kt
  await/src/test/java/com/adyen/checkout/await/internal/ui/DefaultAwaitDelegateTest.kt
Labels: Chore

#1635 Fix sonar
  .github/workflows/sonar_cloud.yml
  dependencies.gradle
  gradle/verification-metadata.xml
Labels: Chore

#1630 Integrate with Twint SDK
  RELEASE_NOTES.md
  action-core/build.gradle
  action-core/src/main/java/com/adyen/checkout/action/core/GenericActionConfiguration.kt
  action-core/src/main/java/com/adyen/checkout/action/core/internal/ActionHandlingConfigurationBuilder.kt
  action-core/src/main/java/com/adyen/checkout/action/core/internal/ActionHandlingPaymentMethodConfigurationBuilder.kt
  action-core/src/main/java/com/adyen/checkout/action/core/internal/provider/ActionComponentExtensions.kt
  action-core/src/main/java/com/adyen/checkout/action/core/internal/ui/ActionDelegateProvider.kt
  action-core/src/test/java/com/adyen/checkout/action/core/internal/ui/ActionDelegateProviderTest.kt
  boleto/src/main/java/com/adyen/checkout/boleto/internal/ui/DefaultBoletoDelegate.kt
  components-core/src/main/java/com/adyen/checkout/components/core/PaymentMethodTypes.kt
  components-core/src/main/java/com/adyen/checkout/components/core/action/SdkAction.kt
  components-core/src/main/java/com/adyen/checkout/components/core/action/TwintSdkData.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/util/StatusResponseUtils.kt
  components-core/src/main/java/com/adyen/checkout/components/core/paymentmethod/GenericPaymentMethod.kt
  components-core/src/test/java/com/adyen/checkout/components/core/PaymentComponentDataTest.kt
  components-core/src/test/java/com/adyen/checkout/components/core/action/TwintSdkDataTest.kt
  drop-in/build.gradle
  drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
  econtext/build.gradle
  example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/instant/InstantFragment.kt
  instant/src/main/java/com/adyen/checkout/instant/ActionHandlingMethod.kt
  instant/src/main/java/com/adyen/checkout/instant/InstantPaymentConfiguration.kt
  instant/src/main/java/com/adyen/checkout/instant/internal/provider/InstantPaymentComponentProvider.kt
  instant/src/main/java/com/adyen/checkout/instant/internal/ui/DefaultInstantPaymentDelegate.kt
  instant/src/main/java/com/adyen/checkout/instant/internal/ui/model/InstantComponentParams.kt
  instant/src/main/java/com/adyen/checkout/instant/internal/ui/model/InstantComponentParamsMapper.kt
  instant/src/test/java/com/adyen/checkout/instant/InstantPaymentConfigurationTest.kt
  instant/src/test/java/com/adyen/checkout/instant/internal/ui/DefaultInstantPaymentDelegateTest.kt
  instant/src/test/java/com/adyen/checkout/instant/internal/ui/model/InstantComponentParamsMapperTest.kt
  issuer-list/build.gradle
  settings.gradle
  twint/build.gradle
  twint/consumer-rules.pro
  twint/libs/TwintSdk-android-8.0.0.jar
  twint/src/main/AndroidManifest.xml
  twint/src/main/java/com/adyen/checkout/twint/TwintActionComponent.kt
  twint/src/main/java/com/adyen/checkout/twint/TwintActionConfiguration.kt
  twint/src/main/java/com/adyen/checkout/twint/internal/provider/TwintActionComponentProvider.kt
  twint/src/main/java/com/adyen/checkout/twint/internal/ui/DefaultTwintDelegate.kt
  twint/src/main/java/com/adyen/checkout/twint/internal/ui/TwintDelegate.kt
  twint/src/main/java/com/adyen/checkout/twint/internal/ui/TwintFragment.kt
  twint/src/main/java/com/adyen/checkout/twint/internal/ui/TwintView.kt
  twint/src/main/java/com/adyen/checkout/twint/internal/ui/TwintViewProvider.kt
  twint/src/main/res/layout/fragment_twint.xml
  twint/src/main/res/layout/view_twint.xml
  twint/src/test/java/com/adyen/checkout/twint/TwintActionComponentTest.kt
  twint/src/test/java/com/adyen/checkout/twint/TwintActionConfigurationTest.kt
  twint/src/test/java/com/adyen/checkout/twint/internal/ui/DefaultTwintDelegateTest.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/AdyenComponentView.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/ViewProvider.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/PaymentInProgressView.kt
  wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/provider/WeChatPayActionComponentProvider.kt
  wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/ui/DefaultWeChatDelegate.kt
Labels: Feature

#1633 Change phone number country code picker
  docs/UI_CUSTOMIZATION.md
  econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/DefaultEContextDelegate.kt
  econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/EContextDelegate.kt
  econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/view/EContextView.kt
  econtext/src/main/res/layout/econtext_view.xml
  econtext/src/test/java/com/adyen/checkout/econtext/internal/ui/DefaultEContextDelegateTest.kt
  example-app/src/main/res/color/text_color_secondary.xml
  example-app/src/main/res/values/styles.xml
  mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/DefaultMBWayDelegate.kt
  mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/MBWayDelegate.kt
  mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/view/MbWayView.kt
  mbway/src/main/res/layout/mbway_view.xml
  mbway/src/test/java/com/adyen/checkout/mbway/internal/ui/DefaultMBWayDelegateTest.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/CountryViewHolder.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/CountryUtils.kt
  ui-core/src/main/res/color/text_color_secondary.xml
  ui-core/src/main/res/layout/country_view.xml
  ui-core/src/main/res/template/values/strings.xml.tt
  ui-core/src/main/res/values/strings.xml
  ui-core/src/main/res/values/styles.xml
  ui-core/src/test/java/com/adyen/checkout/ui/core/internal/util/CountryUtilsTest.kt
Labels: Chore

#1637 Fix storedPaymentMethod removal for older integrations
  RELEASE_NOTES.md
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/SessionSetupConfiguration.kt
Labels: Fix

#1640 Correctly restore state of WeChatPay
  wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/provider/WeChatPayActionComponentProvider.kt
  wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/ui/DefaultWeChatDelegate.kt
  wechatpay/src/test/java/com/adyen/checkout/wechatpay/internal/ui/DefaultWeChatDelegateTest.kt
Labels: Chore

#1641 Analytics - Remove stored event counter
  components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/DefaultAnalyticsManager.kt
Labels: Chore

#1638 Prepare release 5.4.0
  README.md
  RELEASE_NOTES.md
  dependencies.gradle
  example-app/build.gradle
Labels: Chore

#1643 Add dependency updates to release notes
  RELEASE_NOTES.md
Labels: Chore
