Repository Adyen/adyen-android, pull requests merged in 2024-06, with the labels that each got.

#1661 Update AndroidX Lifecycle to 2.8.2
  dependencies.gradle
  gradle/verification-metadata.xml
Labels: Chore

#1660 Improve address lookup examples
  example-app/src/main/java/com/adyen/checkout/example/repositories/AddressLookupCompletionState.kt
  example-app/src/main/java/com/adyen/checkout/example/repositories/AddressLookupRepository.kt
  example-app/src/main/java/com/adyen/checkout/example/service/ExampleAdvancedDropInService.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/CardActivity.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/CardViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardTakenOverActivity.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardTakenOverViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardUiState.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/compose/SessionsCardScreen.kt
Labels: Chore

#1665 Public api validation
  .github/workflows/check_pr.yml
  .github/workflows/validate_public_api.yml
  3ds2/api/3ds2.api
  ach/api/ach.api
  action-core/api/action-core.api
  await/api/await.api
  bacs/api/bacs.api
  bcmc/api/bcmc.api
  blik/api/blik.api
  boleto/api/boleto.api
  build.gradle
  card/api/card.api
  cashapppay/api/cashapppay.api
  checkout-core/api/checkout-core.api
  components-compose/api/components-compose.api
  components-core/api/components-core.api
  config/gradle/apiValidator.gradle
  config/gradle/detekt.gradle
  convenience-stores-jp/api/convenience-stores-jp.api
  cse/api/cse.api
  dependencies.gradle
  dotpay/api/dotpay.api
  drop-in-compose/api/drop-in-compose.api
  drop-in/api/drop-in.api
  econtext/api/econtext.api
  entercash/api/entercash.api
  eps/api/eps.api
  giftcard/api/giftcard.api
  googlepay/api/googlepay.api
  gradle/verification-metadata.xml
  ideal/api/ideal.api
  instant/api/instant.api
  issuer-list/api/issuer-list.api
  mbway/api/mbway.api
  molpay/api/molpay.api
  online-banking-core/api/online-banking-core.api
  online-banking-cz/api/online-banking-cz.api
  online-banking-jp/api/online-banking-jp.api
  online-banking-pl/api/online-banking-pl.api
  online-banking-sk/api/online-banking-sk.api
  openbanking/api/openbanking.api
  paybybank/api/paybybank.api
  payeasy/api/payeasy.api
  qr-code/api/qr-code.api
  redirect/api/redirect.api
  scripts/process_api_changes.sh
  sepa/api/sepa.api
  sessions-core/api/sessions-core.api
  seven-eleven/api/seven-eleven.api
  twint/api/twint.api
  ui-core/api/ui-core.api
  upi/api/upi.api
  voucher/api/voucher.api
  wechatpay/api/wechatpay.api
Labels: Chore

#1668 Simplify api change formatting
  scripts/process_api_changes.sh
Labels: Chore

#1636 Implement Ideal 2.0 flow
  RELEASE_NOTES.md
  ideal/api/ideal.api
  ideal/build.gradle
  ideal/src/main/java/com/adyen/checkout/ideal/IdealComponent.kt
  ideal/src/main/java/com/adyen/checkout/ideal/IdealConfiguration.kt
  ideal/src/main/java/com/adyen/checkout/ideal/internal/provider/IdealComponentProvider.kt
  ideal/src/main/java/com/adyen/checkout/ideal/internal/ui/DefaultIdealDelegate.kt
  ideal/src/main/java/com/adyen/checkout/ideal/internal/ui/IdealDelegate.kt
  ideal/src/test/java/com/adyen/checkout/ideal/IdealComponentTest.kt
  ideal/src/test/java/com/adyen/checkout/ideal/internal/ui/DefaultIdealDelegateTest.kt
  issuer-list/api/issuer-list.api
  issuer-list/src/main/java/com/adyen/checkout/issuerlist/internal/IssuerListConfiguration.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/DefaultRedirectHandler.kt
Labels: Feature

#1658 Extend autofill support
  RELEASE_NOTES.md
  dependencies.gradle
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/view/GiftCardNumberInput.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/view/GiftCardView.kt
  gradle/verification-metadata.xml
  ui-core/build.gradle
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/AddressFormInput.kt
  ui-core/src/main/res/layout/address_form_br.xml
  ui-core/src/main/res/layout/address_form_ca.xml
  ui-core/src/main/res/layout/address_form_default.xml
  ui-core/src/main/res/layout/address_form_gb.xml
  ui-core/src/main/res/layout/address_form_input.xml
  ui-core/src/main/res/layout/address_form_us.xml
  upi/src/main/java/com/adyen/checkout/upi/internal/ui/view/UPIIntentManualAddressViewHolder.kt
  upi/src/main/java/com/adyen/checkout/upi/internal/ui/view/UPIView.kt
Labels: Feature

#1672 Improve Renovate Kotlin grouping
  renovate.json
Labels: Chore

#1673 Fix minification for compileOnly dependencies
  RELEASE_NOTES.md
  action-core/consumer-rules.pro
Labels: Fix
