Repository Adyen/adyen-android, pull requests merged in 2024-07, with the labels that each got.

#1664 Add 3DS2 version to Google Pay component data
  RELEASE_NOTES.md
  action-core/build.gradle
  action-core/src/test/java/com/adyen/threeds2/ThreeDS2Service.kt
  action-core/src/testFixtures/java/com/adyen/threeds2/ThreeDS2Service.java
  bcmc/build.gradle
  card/build.gradle
  card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
  card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
  components-core/api/components-core.api
  components-core/src/main/java/com/adyen/checkout/components/core/paymentmethod/GooglePayPaymentMethod.kt
  googlepay/build.gradle
  googlepay/src/main/java/com/adyen/checkout/googlepay/internal/util/GooglePayUtils.kt
  googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegateTest.kt
Labels: Feature

#1693 Preparing release 5.6.0
  README.md
  RELEASE_NOTES.md
  dependencies.gradle
  example-app/build.gradle
Labels: Chore

#1687 Update 3DS2 SDK to 2.2.19 (v4)
  RELEASE_NOTES.md
  build.gradle
  config/gradle/checksums.gradle
  example-app/build.gradle
Labels: Dependencies

#1692 Rename Twint classes
  action-core/src/test/java/com/adyen/checkout/action/core/internal/ui/ActionDelegateProviderTest.kt
  twint/api/twint.api
  twint/src/main/java/com/adyen/checkout/twint/TwintActionComponent.kt
  twint/src/main/java/com/adyen/checkout/twint/internal/provider/TwintActionComponentProvider.kt
  twint/src/main/java/com/adyen/checkout/twint/internal/ui/DefaultTwintActionDelegate.kt
  twint/src/main/java/com/adyen/checkout/twint/internal/ui/TwintActionDelegate.kt
  twint/src/main/java/com/adyen/checkout/twint/internal/ui/TwintActionFragment.kt
  twint/src/main/java/com/adyen/checkout/twint/internal/ui/TwintActionView.kt
  twint/src/main/java/com/adyen/checkout/twint/internal/ui/TwintActionViewProvider.kt
  twint/src/main/res/layout/fragment_twint_action.xml
  twint/src/main/res/layout/view_twint_action.xml
  twint/src/test/java/com/adyen/checkout/twint/TwintActionComponentTest.kt
  twint/src/test/java/com/adyen/checkout/twint/internal/ui/DefaultTwintActionDelegateTest.kt
Labels: Chore

#1699 Update drop-in preview screenshot
  README.md
Labels: Chore

#1702 Improve toolbar accessibility
  RELEASE_NOTES.md
  drop-in/src/main/res/template/values/strings.xml.tt
  drop-in/src/main/res/values-ar/strings.xml
  drop-in/src/main/res/values-cs-rCZ/strings.xml
  drop-in/src/main/res/values-da-rDK/strings.xml
  drop-in/src/main/res/values-de-rDE/strings.xml
  drop-in/src/main/res/values-el-rGR/strings.xml
  drop-in/src/main/res/values-es-rES/strings.xml
  drop-in/src/main/res/values-fi-rFI/strings.xml
  drop-in/src/main/res/values-fr-rFR/strings.xml
  drop-in/src/main/res/values-hr-rHR/strings.xml
  drop-in/src/main/res/values-hu-rHU/strings.xml
  drop-in/src/main/res/values-it-rIT/strings.xml
  drop-in/src/main/res/values-ja-rJP/strings.xml
  drop-in/src/main/res/values-ko-rKR/strings.xml
  drop-in/src/main/res/values-nb-rNO/strings.xml
  drop-in/src/main/res/values-nl-rNL/strings.xml
  drop-in/src/main/res/values-pl-rPL/strings.xml
  drop-in/src/main/res/values-pt-rBR/strings.xml
  drop-in/src/main/res/values-pt-rPT/strings.xml
  drop-in/src/main/res/values-ro-rRO/strings.xml
  drop-in/src/main/res/values-ru-rRU/strings.xml
  drop-in/src/main/res/values-sk-rSK/strings.xml
  drop-in/src/main/res/values-sl-rSI/strings.xml
  drop-in/src/main/res/values-sv-rSE/strings.xml
  drop-in/src/main/res/values-zh-rCN/strings.xml
  drop-in/src/main/res/values-zh-rTW/strings.xml
  drop-in/src/main/res/values/strings.xml
  drop-in/src/main/res/values/styles.xml
Labels: Fix

#1659 Setup UI test networking
  dependencies.gradle
  drop-in/src/main/res/layout/activity_drop_in.xml
  example-app/build.gradle
  example-app/src/androidTest/assets/public_key_response.json
  example-app/src/androidTest/assets/sessions_response.json
  example-app/src/androidTest/assets/sessions_setup_response.json
  example-app/src/androidTest/java/com/adyen/checkout/MainTest.kt
  example-app/src/androidTest/java/com/adyen/checkout/dropin/DropInTest.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/HiltTestRunner.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/di/FakeBaseUrlModule.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/di/FakeConfigurationModule.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/fake/FakeCheckoutConfigurationProvider.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/robot/DropInRobot.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/robot/MainRobot.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/robot/TestRobot.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/rule/CheckoutTestRule.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/rule/IdlingDispatcherRule.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/rule/MockServerRule.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/server/CheckoutMockWebServer.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/server/DelegatingBackendDispatcher.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/server/service/MockBackendService.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/server/service/MockCheckoutService.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/server/service/MockPublicKeyService.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/server/service/MockSessionService.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/util/IdlingResourceDispatcher.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/util/JsonFileReader.kt
  example-app/src/main/java/com/adyen/checkout/example/di/ConfigurationModule.kt
  example-app/src/main/java/com/adyen/checkout/example/di/NetworkModule.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/configuration/ConfigurationProvider.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/main/MainViewModel.kt
  example-app/src/main/res/layout/activity_main.xml
  gradle/verification-metadata.xml
Labels: Chore

#1706 Meal voucher - Create mealvoucher module
  mealvoucher/.gitignore
  mealvoucher/build.gradle
  mealvoucher/consumer-rules.pro
  mealvoucher/proguard-rules.pro
  mealvoucher/src/main/AndroidManifest.xml
  settings.gradle
Labels: Chore

#1712 Update support contact section in readme
  README.md
Labels: Chore

#1711 Implement MealVoucherComponentProvider and MealVoucherComponent
  components-core/api/components-core.api
  components-core/src/main/java/com/adyen/checkout/components/core/PaymentMethodTypes.kt
  giftcard/api/giftcard.api
  giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardComponent.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardConfiguration.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/GiftCardComponentEventHandler.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/SessionsGiftCardComponentCallbackWrapper.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegate.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/GiftCardDelegate.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardComponentParams.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardComponentParamsMapper.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardInputData.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardOutputData.kt
  mealvoucher/api/mealvoucher.api
  mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/MealVoucherComponent.kt
  mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/provider/MealVoucherComponentProvider.kt
Labels: Chore

#1713 Implement MealVoucherViewProvider
  components-core/src/main/java/com/adyen/checkout/components/core/PaymentMethodTypes.kt
  drop-in/build.gradle
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/provider/ComponentProvider.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/provider/FragmentProvider.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/provider/GiftCardComponentProvider.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegate.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/GiftCardViewProvider.kt
  giftcard/src/test/java/com/adyen/checkout/giftcard/GiftCardComponentTest.kt
  giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegateTest.kt
  mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/provider/MealVoucherComponentProvider.kt
  mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/ui/MealVoucherViewProvider.kt
  mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/ui/view/MealVoucherView.kt
Labels: Chore

#1715 Meal voucher - Create MealVoucherView
  bcmc/src/main/res/layout/bcmc_view.xml
  card/api/card.api
  card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/StoredCardDelegate.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/model/CardInputData.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/model/CardOutputData.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardNumberInput.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardView.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/view/StoredCardView.kt
  card/src/main/java/com/adyen/checkout/card/internal/util/CardValidationUtils.kt
  card/src/main/res/layout/card_view.xml
  card/src/main/res/layout/stored_card_view.xml
  card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
  card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
  card/src/test/java/com/adyen/checkout/card/internal/util/CardValidationUtilsTest.kt
  giftcard/api/giftcard.api
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/view/GiftCardNumberInput.kt
  mealvoucher/api/mealvoucher.api
  mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/ui/view/MealVoucherView.kt
  mealvoucher/src/main/res/layout/meal_voucher_view.xml
  mealvoucher/src/main/res/values/strings.xml
  mealvoucher/src/main/res/values/styles.xml
  ui-core/api/ui-core.api
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/model/ExpiryDate.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/ExpiryDateInput.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/SecurityCodeInput.kt
Labels: Chore

#1717 Meal voucher - Implement expiry date validation and extract validation logic to GiftCardValidator
  card/src/main/java/com/adyen/checkout/card/internal/util/CardValidationUtils.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/provider/GiftCardComponentProvider.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegate.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/DefaultGiftCardValidator.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardNumberUtils.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardPinUtils.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardValidator.kt
  giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegateTest.kt
  mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/provider/MealVoucherComponentProvider.kt
  mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/ui/view/MealVoucherView.kt
  mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/util/MealVoucherValidationUtils.kt
  mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/util/MealVoucherValidator.kt
  mealvoucher/src/main/res/values/strings.xml
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/ExpiryDateValidationResult.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/ExpiryDateValidationUtils.kt
Labels: Chore
