Repository Adyen/adyen-android, pull requests merged in 2024-10, with the labels that each got.

#1801 Analytics - Always make the initial analytics call
  components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/DefaultAnalyticsManager.kt
  components-core/src/test/java/com/adyen/checkout/components/core/internal/analytics/DefaultAnalyticsManagerTest.kt
Labels: Chore

#1799 Add action to manage stale issues
  .github/workflows/stale_issues.yml
Labels: Chore

#1798 Analytics - Fix malformed locale in analytics setup request
  components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/data/remote/DefaultAnalyticsSetupProvider.kt
  components-core/src/test/java/com/adyen/checkout/components/core/internal/analytics/data/remote/DefaultAnalyticsSetupProviderTest.kt
Labels: Chore

#1807 Don't fallback to normal redirect flow
  redirect/src/main/java/com/adyen/checkout/redirect/internal/data/model/NativeRedirectRequest.kt
  redirect/src/main/java/com/adyen/checkout/redirect/internal/ui/DefaultRedirectDelegate.kt
Labels: Chore

#1802 Analytics - Send failed checkoutAttemptId if fetching fails
  components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/DefaultAnalyticsManager.kt
  components-core/src/test/java/com/adyen/checkout/components/core/internal/analytics/DefaultAnalyticsManagerTest.kt
Labels: Chore

#1809 Correctly check nullability when reading from JSON objects
  RELEASE_NOTES.md
  checkout-core/src/main/java/com/adyen/checkout/core/internal/data/model/JsonUtils.kt
  checkout-core/src/test/java/com/adyen/checkout/core/internal/data/model/JsonUtilsTest.kt
Labels: Fix

#1810 Document Adyen Test Cards
  README.md
  RELEASE_NOTES.md
Labels: Chore

#1813 Add Twint to payment methods docs readme
  docs/payment-methods/README.md
Labels: Chore

#1817 Explicitly include androidx.activity in gradle build
  RELEASE_NOTES.md
  components-core/build.gradle
  dependencies.gradle
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
  gradle/verification-metadata.xml
Labels: Dependencies

#1821 Restrict CardNumberValidator.MAXIMUM_CARD_NUMBER_LENGTH to library group
  checkout-core/api/checkout-core.api
  checkout-core/src/main/java/com/adyen/checkout/core/ui/validation/CardNumberValidator.kt
Labels: Chore

#1822 Fix expiry date autofill hint
  card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardView.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/ExpiryDateInput.kt
Labels: Chore

#1823 Remove unused bcmc layout file
  bcmc/src/main/res/layout/bcmc_view.xml
Labels: Chore

#1824 Fix layout alignment issue when security code is hidden in meal vouchers
  meal-voucher-fr/src/main/java/com/adyen/checkout/mealvoucherfr/internal/ui/view/MealVoucherFRView.kt
Labels: Chore

#1818 Prepare release 5.7.0
  README.md
  RELEASE_NOTES.md
  dependencies.gradle
  example-app/build.gradle
Labels: Chore

#1826 Update drop-in preview screenshots in readme
  README.md
Labels: Chore

#1827 Link to docs in analytics level
  components-core/src/main/java/com/adyen/checkout/components/core/AnalyticsConfiguration.kt
Labels: Chore

#1831 Explicitly add compose compiler dependency in libs.versions.toml
  gradle/libs.versions.toml
Labels: Chore

#1820 Google Pay button styling
  example-app/src/main/res/values/styles.xml
  googlepay/api/googlepay.api
  googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayButtonStyling.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayConfiguration.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/GooglePayButtonView.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/GooglePayDelegate.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParams.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParamsMapper.kt
  googlepay/src/main/res/layout/view_google_pay_button.xml
  googlepay/src/main/res/values-night/styles.xml
  googlepay/src/main/res/values/attrs.xml
  googlepay/src/main/res/values/styles.xml
  googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParamsMapperTest.kt
  googlepay/src/test/java/com/adyen/checkout/googlepay/internal/util/GooglePayUtilsTest.kt
Labels: Chore

#1833 Uncomment previously failing 3DS2 tests
  3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
  3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/SharedChallengeStatusHandlerTest.kt
  gradle/libs.versions.toml
Labels: Chore

#1840 Correctly read checkout version from version catalog
  config/gradle/buildConfig.gradle
Labels: Chore

#1841 Replace prefill with autofill for test cards app in readme
  README.md
Labels: Chore

#1844 Pay By Bank US - Create module
  paybybank-us/.gitignore
  paybybank-us/api/paybybank-us.api
  paybybank-us/build.gradle
  paybybank-us/consumer-rules.pro
  paybybank-us/proguard-rules.pro
  paybybank-us/src/main/AndroidManifest.xml
  paybybank-us/src/main/java/com/adyen/checkout/paybybankus/PayByBankUSComponent.kt
  paybybank-us/src/main/java/com/adyen/checkout/paybybankus/PayByBankUSComponentState.kt
  paybybank-us/src/main/java/com/adyen/checkout/paybybankus/PayByBankUSConfiguration.kt
  paybybank-us/src/main/java/com/adyen/checkout/paybybankus/internal/DefaultPayByBankUSDelegate.kt
  paybybank-us/src/main/java/com/adyen/checkout/paybybankus/internal/PayByBankUSDelegate.kt
  paybybank-us/src/main/java/com/adyen/checkout/paybybankus/internal/PayByBankUSViewProvider.kt
  paybybank-us/src/main/java/com/adyen/checkout/paybybankus/internal/provider/PayByBankUSComponentProvider.kt
  paybybank-us/src/main/java/com/adyen/checkout/paybybankus/internal/ui/model/PayByBankUSInputData.kt
  paybybank-us/src/main/java/com/adyen/checkout/paybybankus/internal/ui/model/PayByBankUSOutputData.kt
  paybybank-us/src/main/java/com/adyen/checkout/paybybankus/internal/ui/view/PayByBankUSView.kt
  settings.gradle
Labels: Chore

#1848 Version catalogs - Fix version name script
  scripts/version_name.sh
Labels: Chore

#1842 Introduce DispatcherProvider
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/data/api/SubmitFingerprintService.kt
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/provider/Adyen3DS2ComponentProvider.kt
  card/src/main/java/com/adyen/checkout/card/internal/data/api/BinLookupService.kt
  cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/ui/DefaultCashAppPayDelegate.kt
  checkout-core/src/main/java/com/adyen/checkout/core/DispatcherProvider.kt
  checkout-core/src/main/java/com/adyen/checkout/core/internal/ui/ImageLoader.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/DefaultAnalyticsManager.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsService.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/OrderStatusService.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/PublicKeyService.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/StatusRepository.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/service/BaseDropInService.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInViewModel.kt
  example-app/src/androidTest/java/com/adyen/checkout/test/rule/IdlingDispatcherRule.kt
  redirect/src/main/java/com/adyen/checkout/redirect/internal/data/api/NativeRedirectService.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/CheckoutSessionInitializer.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/api/SessionService.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/data/api/AddressService.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/data/api/DefaultAddressRepository.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/ImageSaver.kt
Labels: Chore

#1845 Pay By Bank US - Implement configuration
  components-core/api/components-core.api
  components-core/src/main/java/com/adyen/checkout/components/core/PaymentMethodTypes.kt
  paybybank-us/api/paybybank-us.api
  paybybank-us/src/main/java/com/adyen/checkout/paybybankus/PayByBankUSConfiguration.kt
  paybybank-us/src/test/java/com/adyen/checkout/paybybankus/PayByBankUSConfigurationTest.kt
Labels: Chore

#1815 Replace JSONObject's opt functions with nullable extensions
  checkout-core/src/main/java/com/adyen/checkout/core/internal/data/model/ErrorResponseBody.kt
  components-core/src/main/java/com/adyen/checkout/components/core/Amount.kt
  components-core/src/main/java/com/adyen/checkout/components/core/Installments.kt
  components-core/src/main/java/com/adyen/checkout/components/core/Issuer.kt
  components-core/src/main/java/com/adyen/checkout/components/core/OrderRequest.kt
  components-core/src/main/java/com/adyen/checkout/components/core/OrderResponse.kt
  components-core/src/main/java/com/adyen/checkout/components/core/PaymentComponentData.kt
  components-core/src/main/java/com/adyen/checkout/components/core/action/Action.kt
  components-core/src/main/java/com/adyen/checkout/components/core/action/TwintSdkData.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/data/model/PublicKeyResponse.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/BillingAddressParameters.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/ShippingAddressParameters.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/internal/data/model/CardParameters.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/internal/data/model/IsReadyToPayRequestModel.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/internal/data/model/PaymentDataRequestModel.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/internal/util/GooglePayUtils.kt
  lint/src/main/java/com/adyen/checkout/lint/JSONOptFunctions.kt
  lint/src/main/java/com/adyen/checkout/lint/LintIssueRegistry.kt
  lint/src/test/java/com/adyen/checkout/lint/JSONOptFunctionsTest.kt
  redirect/src/main/java/com/adyen/checkout/redirect/internal/ui/DefaultRedirectDelegate.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/SessionModel.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/SessionSetupConfiguration.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/SessionSetupInstallmentOptions.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/SessionSetupResponse.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/model/SessionBalanceRequest.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/model/SessionBalanceResponse.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/model/SessionCancelOrderRequest.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/model/SessionCancelOrderResponse.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/model/SessionDetailsRequest.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/model/SessionDetailsResponse.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/model/SessionDisableTokenRequest.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/model/SessionDisableTokenResponse.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/model/SessionOrderRequest.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/model/SessionOrderResponse.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/model/SessionPaymentsRequest.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/model/SessionPaymentsResponse.kt
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/model/SessionSetupRequest.kt
Labels: Chore

#1851 Replace usage of Dispatchers with DispatcherProvider in example app
  example-app/src/main/java/com/adyen/checkout/example/repositories/RepositoryUtils.kt
  example-app/src/main/java/com/adyen/checkout/example/service/ExampleAdvancedDropInService.kt
  example-app/src/main/java/com/adyen/checkout/example/service/ExampleDropInService.kt
  example-app/src/main/java/com/adyen/checkout/example/service/ExampleSessionsDropInService.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/bacs/BacsViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/blik/BlikViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/CardViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardTakenOverViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/giftcard/GiftCardViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/GooglePayViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/compose/SessionsGooglePayViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/instant/InstantViewModel.kt
Labels: Chore

#1830 Analytics - Add support for error events
  components-core/api/components-core.api
  components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/AnalyticsEvent.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/AnalyticsManagerFactory.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/ErrorEvent.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/GenericEvents.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/data/DefaultAnalyticsRepository.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/data/local/ErrorAnalyticsLocalDataStore.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/data/remote/AnalyticsRemoteDataStore.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/data/remote/AnalyticsTrackRequestProvider.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/data/remote/DefaultAnalyticsRemoteDataStore.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/data/model/AnalyticsTrackError.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/data/model/AnalyticsTrackRequest.kt
  components-core/src/test/java/com/adyen/checkout/components/core/internal/analytics/data/DefaultAnalyticsRepositoryTest.kt
  components-core/src/test/java/com/adyen/checkout/components/core/internal/analytics/data/remote/AnalyticsTrackRequestProviderTest.kt
  components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsServiceTest.kt
  components-core/src/test/java/com/adyen/checkout/components/core/internal/data/model/AnalyticsTrackRequestTest.kt
Labels: Chore
