Repository Adyen/adyen-android, pull requests merged in 2024-01, with the labels that each got.

#1431 Update kotlin and compose dependencies
  dependencies.gradle
  gradle/verification-metadata.xml
Labels: Dependencies

#1350 Implement JWE encryption
  ach/src/main/java/com/adyen/checkout/ach/internal/provider/ACHDirectDebitComponentProvider.kt
  ach/src/main/java/com/adyen/checkout/ach/internal/ui/DefaultACHDirectDebitDelegate.kt
  ach/src/test/java/com/adyen/checkout/ach/internal/ui/DefaultACHDirectDebitDelegateTest.kt
  bcmc/src/main/java/com/adyen/checkout/bcmc/internal/provider/BcmcComponentProvider.kt
  card/src/main/java/com/adyen/checkout/card/internal/data/api/DefaultDetectCardTypeRepository.kt
  card/src/main/java/com/adyen/checkout/card/internal/provider/CardComponentProvider.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/StoredCardDelegate.kt
  card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
  card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
  cse/build.gradle
  cse/src/main/java/com/adyen/checkout/cse/CardEncrypter.kt
  cse/src/main/java/com/adyen/checkout/cse/GenericEncrypter.kt
  cse/src/main/java/com/adyen/checkout/cse/internal/BaseCardEncryptor.kt
  cse/src/main/java/com/adyen/checkout/cse/internal/BaseGenericEncryptor.kt
  cse/src/main/java/com/adyen/checkout/cse/internal/CardEncryptorFactory.kt
  cse/src/main/java/com/adyen/checkout/cse/internal/ClientSideEncrypter.kt
  cse/src/main/java/com/adyen/checkout/cse/internal/CompositeKey.kt
  cse/src/main/java/com/adyen/checkout/cse/internal/DateGenerator.kt
  cse/src/main/java/com/adyen/checkout/cse/internal/DefaultCardEncryptor.kt
  cse/src/main/java/com/adyen/checkout/cse/internal/DefaultGenericEncryptor.kt
  cse/src/main/java/com/adyen/checkout/cse/internal/GenericEncryptorFactory.kt
  cse/src/main/java/com/adyen/checkout/cse/internal/JSONWebEncryptor.kt
  cse/src/main/java/com/adyen/checkout/cse/internal/JWEObject.kt
  cse/src/main/java/com/adyen/checkout/cse/internal/test/TestCardEncryptor.kt
  cse/src/main/java/com/adyen/checkout/cse/internal/test/TestGenericEncryptor.kt
  cse/src/test/java/com/adyen/checkout/cse/internal/DefaultCardEncryptorTest.kt
  cse/src/test/java/com/adyen/checkout/cse/internal/DefaultGenericEncryptorTest.kt
  cse/src/test/java/com/adyen/checkout/cse/internal/JSONWebEncryptorTest.kt
  dependencies.gradle
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/provider/GiftCardComponentProvider.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegate.kt
  giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegateTest.kt
  gradle/verification-metadata.xml
Labels: Feature

#1444 Fix error dialog messages
  RELEASE_NOTES.md
  drop-in/src/main/java/com/adyen/checkout/dropin/SessionDropInService.kt
Labels: Fix

#1449 Add missing parent styles in XML
  RELEASE_NOTES.md
  bacs/src/main/res/values/styles.xml
  paybybank/src/main/res/values/styles.xml
  ui-core/src/main/res/values/styles.xml
  upi/src/main/res/values/styles.xml
  voucher/src/main/res/values/styles.xml
Labels: Fix

#1453 Fix polling interval values in polling action components
  RELEASE_NOTES.md
  components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/StatusRepository.kt
Labels: Fix
