Repository Adyen/adyen-android, pull requests merged in 2025-07, with the labels that each got.

#2180 Sonatype - Add a step to move repository from Staging API to Central Portal
  .github/workflows/publish_to_maven_central.yml
  scripts/move_ossrh_repository_to_central_portal.py
Labels: Chore

#2191 Sonatype - Clean up scripts
  scripts/drop_all_open_ossrh_repositories.py
  scripts/move_ossrh_repository_to_central_portal.py
Labels: Chore

#2197 V5 - Update Support URL in README.md
  README.md
  SUPPORT.md
Labels: Chore

#2198 v6 - Disable co-badged for not supported brands
  card/api/card.api
  card/src/main/java/com/adyen/checkout/card/internal/ui/model/DualBrandData.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardView.kt
  card/src/main/java/com/adyen/checkout/card/internal/util/DualBrandedCardHandler.kt
  card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
  card/src/test/java/com/adyen/checkout/card/internal/util/DualBrandedCardHandlerTest.kt
Labels: Chore

#2188 v6 - Stepper UI
  .github/release_notes_dependency_list.toml
  gradle/libs.versions.toml
  gradle/verification-metadata.xml
  ui/api/ui.api
  ui/build.gradle
  ui/src/main/java/com/adyen/checkout/ui/internal/Stepper.kt
  ui/src/main/res/drawable/ic_rounded_square.xml
Labels: Chore

#2204 V5 - Release - Add the commit to the release action
  .github/workflows/create_github_release.yml
  .github/workflows/finalize_release.yml
Labels: Chore

#2205 V6 - Release - Add the commit to the release action
  .github/workflows/create_github_release.yml
  .github/workflows/finalize_release.yml
Labels: Chore

#2202 v6 - Move core test class to test fixtures
  core/src/test/java/com/adyen/checkout/core/common/internal/ui/state/DefaultDelegateStateManagerTest.kt
  core/src/testFixtures/java/com/adyen/checkout/test/ui/state/TestFieldTransformerRegistry.kt
  mbway/build.gradle
  mbway/src/test/java/com/adyen/checkout/mbway/internal/ui/MBWayComponentStateTest.kt
Labels: Chore

#2203 v6 - Register MBWay factory
  .github/release_notes_dependency_list.toml
  core/src/main/java/com/adyen/checkout/core/components/internal/PaymentMethodProvider.kt
  gradle/libs.versions.toml
  gradle/verification-metadata.xml
  mbway/build.gradle
  mbway/src/main/AndroidManifest.xml
  mbway/src/main/java/com/adyen/checkout/mbway/internal/MBWayInitializer.kt
Labels: Chore

#2211 V6 - Action - Move action to core
  core/api/core.api
  core/src/main/java/com/adyen/checkout/core/action/data/Action.kt
  core/src/main/java/com/adyen/checkout/core/sessions/SessionPaymentResult.kt
  core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionCallResult.kt
  core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionInteractor.kt
  core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionsComponentEventHandler.kt
  core/src/main/java/com/adyen/checkout/core/sessions/internal/data/model/SessionPaymentsResponse.kt
Labels: Chore

#2213 V6 - Action - Move result handling to payment facilitator
  core/api/core.api
  core/src/main/java/com/adyen/checkout/core/components/CheckoutResult.kt
  core/src/main/java/com/adyen/checkout/core/components/internal/AdvancedComponentEventHandler.kt
  core/src/main/java/com/adyen/checkout/core/components/internal/ComponentEventHandler.kt
  core/src/main/java/com/adyen/checkout/core/components/internal/PaymentFacilitator.kt
  core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionsComponentEventHandler.kt
Labels: Chore

#2210 v5 - Checkout configuration isSubmitButtonVisible
  ach/src/main/java/com/adyen/checkout/ach/ACHDirectDebitConfiguration.kt
  ach/src/main/java/com/adyen/checkout/ach/internal/ui/model/ACHDirectDebitComponentParamsMapper.kt
  ach/src/test/java/com/adyen/checkout/ach/internal/ui/model/ACHDirectDebitComponentParamsMapperTest.kt
  bacs/src/main/java/com/adyen/checkout/bacs/BacsDirectDebitConfiguration.kt
  bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcConfiguration.kt
  bcmc/src/main/java/com/adyen/checkout/bcmc/internal/ui/model/BcmcComponentParamsMapper.kt
  bcmc/src/test/java/com/adyen/checkout/bcmc/internal/ui/model/BcmcComponentParamsMapperTest.kt
  blik/src/main/java/com/adyen/checkout/blik/BlikConfiguration.kt
  boleto/src/main/java/com/adyen/checkout/boleto/BoletoConfiguration.kt
  boleto/src/main/java/com/adyen/checkout/boleto/internal/ui/model/BoletoComponentParamsMapper.kt
  boleto/src/test/java/com/adyen/checkout/boleto/internal/ui/model/BoletoComponentParamsMapperTest.kt
  card/src/main/java/com/adyen/checkout/card/CardConfiguration.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/model/CardComponentParamsMapper.kt
  card/src/test/java/com/adyen/checkout/card/internal/ui/model/CardComponentParamsMapperTest.kt
  cashapppay/src/main/java/com/adyen/checkout/cashapppay/CashAppPayConfiguration.kt
  cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/ui/model/CashAppPayComponentParamsMapper.kt
  cashapppay/src/test/java/com/adyen/checkout/cashapppay/internal/ui/model/CashAppPayComponentParamsMapperTest.kt
  components-core/api/components-core.api
  components-core/src/main/java/com/adyen/checkout/components/core/CheckoutConfiguration.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/ButtonComponentParamsMapper.kt
  components-core/src/test/java/com/adyen/checkout/components/core/CheckoutConfigurationTest.kt
  components-core/src/test/java/com/adyen/checkout/components/core/internal/ui/model/ButtonComponentParamsMapperTest.kt
  convenience-stores-jp/src/main/java/com/adyen/checkout/conveniencestoresjp/ConvenienceStoresJPConfiguration.kt
  dotpay/src/main/java/com/adyen/checkout/dotpay/DotpayConfiguration.kt
  entercash/src/main/java/com/adyen/checkout/entercash/EntercashConfiguration.kt
  eps/src/main/java/com/adyen/checkout/eps/EPSConfiguration.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardConfiguration.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardComponentParamsMapper.kt
  giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardComponentParamsMapperTest.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayConfiguration.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParamsMapper.kt
  googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParamsMapperTest.kt
  issuer-list/src/main/java/com/adyen/checkout/issuerlist/internal/ui/model/IssuerListComponentParamsMapper.kt
  issuer-list/src/test/java/com/adyen/checkout/issuerlist/internal/ui/model/IssuerListComponentParamsMapperTest.kt
  mbway/src/main/java/com/adyen/checkout/mbway/MBWayConfiguration.kt
  meal-voucher-fr/src/main/java/com/adyen/checkout/mealvoucherfr/MealVoucherFRConfiguration.kt
  meal-voucher-fr/src/main/java/com/adyen/checkout/mealvoucherfr/internal/ui/model/MealVoucherFRComponentParamsMapper.kt
  meal-voucher-fr/src/test/java/com/adyen/checkout/mealvoucherfr/internal/ui/model/MealVoucherFRComponentParamsMapperTest.kt
  molpay/src/main/java/com/adyen/checkout/molpay/MolpayConfiguration.kt
  online-banking-cz/src/main/java/com/adyen/checkout/onlinebankingcz/OnlineBankingCZConfiguration.kt
  online-banking-jp/src/main/java/com/adyen/checkout/onlinebankingjp/OnlineBankingJPConfiguration.kt
  online-banking-pl/src/main/java/com/adyen/checkout/onlinebankingpl/OnlineBankingPLConfiguration.kt
  online-banking-sk/src/main/java/com/adyen/checkout/onlinebankingsk/OnlineBankingSKConfiguration.kt
  openbanking/src/main/java/com/adyen/checkout/openbanking/OpenBankingConfiguration.kt
  payeasy/src/main/java/com/adyen/checkout/payeasy/PayEasyConfiguration.kt
  payto/src/main/java/com/adyen/checkout/payto/PayToConfiguration.kt
  sepa/src/main/java/com/adyen/checkout/sepa/SepaConfiguration.kt
  seven-eleven/src/main/java/com/adyen/checkout/seveneleven/SevenElevenConfiguration.kt
  twint/src/main/java/com/adyen/checkout/twint/TwintConfiguration.kt
  twint/src/main/java/com/adyen/checkout/twint/internal/ui/model/TwintComponentParamsMapper.kt
  twint/src/test/java/com/adyen/checkout/twint/internal/ui/model/TwintComponentParamsMapperTest.kt
  upi/src/main/java/com/adyen/checkout/upi/UPIConfiguration.kt
Labels: Feature

#2216 v6 - Checkout controller
  core/api/core.api
  core/src/main/java/com/adyen/checkout/core/components/AdyenPaymentFlow.kt
  core/src/main/java/com/adyen/checkout/core/components/CheckoutController.kt
  core/src/main/java/com/adyen/checkout/core/components/internal/AdvancedPaymentFacilitatorFactory.kt
  core/src/main/java/com/adyen/checkout/core/components/internal/AdyenComponent.kt
  core/src/main/java/com/adyen/checkout/core/components/internal/PaymentFacilitator.kt
  core/src/main/java/com/adyen/checkout/core/components/internal/PaymentFacilitatorProvider.kt
  core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionsPaymentFacilitatorFactory.kt
  lint/src/main/java/com/adyen/checkout/lint/ObjectInPublicSealedClass.kt
  lint/src/test/java/com/adyen/checkout/lint/ObjectInPublicSealedClassTest.kt
Labels: Chore

#2228 Escape branch name in add_pr_label.yml
  .github/workflows/add_pr_label.yml
Labels: Chore

#2231 v6 - Apply styling to components
  core/api/core.api
  core/src/main/java/com/adyen/checkout/core/components/AdyenPaymentFlow.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/v6/V6Activity.kt
Labels: Chore

#2234 v6- Move AdyenLogger to core module
  core/api/core.api
  core/src/main/java/com/adyen/checkout/core/common/AdyenLogLevel.kt
  core/src/main/java/com/adyen/checkout/core/common/AdyenLogger.kt
  core/src/main/java/com/adyen/checkout/core/common/internal/helper/AdyenLog.kt
  core/src/main/java/com/adyen/checkout/core/common/internal/helper/LogcatLogger.kt
  core/src/test/java/com/adyen/checkout/core/common/internal/helper/AdyenLoggerTest.kt
  core/src/testFixtures/java/com/adyen/checkout/test/PrintLogger.kt
Labels: Chore

#2235 v6 - Remove AdyenLogger related TODOs
  core/src/main/java/com/adyen/checkout/core/analytics/internal/DefaultAnalyticsManager.kt
  core/src/main/java/com/adyen/checkout/core/analytics/internal/data/DefaultAnalyticsRepository.kt
  core/src/main/java/com/adyen/checkout/core/common/internal/api/HttpClientExt.kt
  core/src/main/java/com/adyen/checkout/core/common/internal/model/JsonUtils.kt
  core/src/main/java/com/adyen/checkout/core/components/internal/PaymentFacilitator.kt
  core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionInteractor.kt
  core/src/main/java/com/adyen/checkout/core/sessions/internal/model/SessionParamsFactory.kt
  core/src/testFixtures/java/com/adyen/checkout/test/LoggingExtension.kt
Labels: Chore

#2232 v6 - Sessions example
  example-app/src/main/AndroidManifest.xml
  example-app/src/main/java/com/adyen/checkout/example/repositories/PaymentsRepository.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardTakenOverViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/giftcard/SessionsGiftCardViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/compose/SessionsGooglePayViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/main/ComponentItem.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/main/ComponentItemProvider.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/main/MainNavigation.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/main/MainViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/v6/V6SessionsActivity.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/v6/V6SessionsViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/v6/V6ViewModel.kt
Labels: Chore

#2240 v6 - Clean up done TODOs
  core/api/core.api
  core/src/main/java/com/adyen/checkout/core/components/internal/AdyenComponent.kt
  core/src/main/java/com/adyen/checkout/core/sessions/CheckoutSession.kt
  core/src/main/java/com/adyen/checkout/core/sessions/SessionPaymentResult.kt
  core/src/main/java/com/adyen/checkout/core/sessions/internal/CheckoutSessionInitializer.kt
  core/src/main/java/com/adyen/checkout/core/sessions/internal/CheckoutSessionProvider.kt
  core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionInteractor.kt
  core/src/main/java/com/adyen/checkout/core/sessions/internal/data/api/SessionRepository.kt
  core/src/main/java/com/adyen/checkout/core/sessions/internal/data/model/SessionSetupRequest.kt
  core/src/test/java/com/adyen/checkout/core/sessions/internal/SessionsComponentEventHandlerTest.kt
  mbway/src/main/java/com/adyen/checkout/mbway/MBWayConfiguration.kt
  mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/MBWayFactory.kt
Labels: Chore

#2245 v5 - Deprecate old 3DS2 actions
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/provider/Adyen3DS2ComponentProvider.kt
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
  3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
  action-core/src/main/java/com/adyen/checkout/action/core/internal/provider/GenericActionComponentProvider.kt
  action-core/src/main/java/com/adyen/checkout/action/core/internal/ui/DefaultGenericActionDelegate.kt
  action-core/src/test/java/com/adyen/checkout/action/core/internal/ui/ActionDelegateProviderTest.kt
  action-core/src/test/java/com/adyen/checkout/action/core/ui/DefaultGenericActionDelegateTest.kt
  components-core/src/main/java/com/adyen/checkout/components/core/action/Action.kt
  components-core/src/main/java/com/adyen/checkout/components/core/action/Threeds2ChallengeAction.kt
  components-core/src/main/java/com/adyen/checkout/components/core/action/Threeds2FingerprintAction.kt
Labels: Chore

#2246 v6 - Update theme structure
  mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/view/MbWayComponent.kt
  ui/api/ui.api
  ui/src/main/java/com/adyen/checkout/ui/internal/AdyenCheckoutTheme.kt
  ui/src/main/java/com/adyen/checkout/ui/internal/AdyenTextFieldDefaults.kt
  ui/src/main/java/com/adyen/checkout/ui/internal/Buttons.kt
  ui/src/main/java/com/adyen/checkout/ui/internal/Stepper.kt
  ui/src/main/java/com/adyen/checkout/ui/internal/Switch.kt
  ui/src/main/java/com/adyen/checkout/ui/theme/AdyenButtonStyles.kt
  ui/src/main/java/com/adyen/checkout/ui/theme/AdyenCheckoutTheme.kt
  ui/src/main/java/com/adyen/checkout/ui/theme/AdyenElements.kt
  ui/src/main/java/com/adyen/checkout/ui/theme/CheckoutAttributes.kt
Labels: Chore

#2251 v5 - Hide keyboard automatically on pay button click
  ui-core/api/ui-core.api
  ui-core/src/main/java/com/adyen/checkout/ui/core/AdyenComponentView.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/PaymentComponentUIState.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/SubmitHandler.kt
  ui-core/src/test/java/com/adyen/checkout/ui/core/internal/ui/SubmitHandlerTest.kt
Labels: Fix

#2256 V6 - Update readme
  README.md
Labels: Chore

#2259 v5 - Include GitHub actions analysis
  .github/workflows/codeql.yml
Labels: Chore

#2258 Include GitHub actions analysis
  .github/workflows/codeql.yml
Labels: Chore
