Repository Adyen/adyen-android, pull requests merged in 2025-02, with the labels that each got.

#1978 PayTo - Create module and initial setup
  await/src/main/java/com/adyen/checkout/await/internal/provider/AwaitComponentProvider.kt
  await/src/main/java/com/adyen/checkout/await/internal/ui/view/AwaitView.kt
  components-core/api/components-core.api
  components-core/src/main/java/com/adyen/checkout/components/core/PaymentMethodTypes.kt
  components-core/src/main/java/com/adyen/checkout/components/core/paymentmethod/PayToPaymentMethod.kt
  components-core/src/main/java/com/adyen/checkout/components/core/paymentmethod/PaymentMethodDetails.kt
  drop-in/build.gradle
  gradle/verification-metadata.xml
  payto/api/payto.api
  payto/build.gradle
  payto/consumer-rules.pro
  payto/src/main/AndroidManifest.xml
  payto/src/main/java/com/adyen/checkout/payto/PayToComponentState.kt
  settings.gradle
Labels: Chore

#1989 PayTo - Create component
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/provider/ComponentProvider.kt
  payto/api/payto.api
  payto/build.gradle
  payto/src/main/java/com/adyen/checkout/payto/PayToComponent.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/provider/PayToComponentProvider.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/PayToDelegate.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/PayToViewProvider.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/view/PayToView.kt
  payto/src/test/java/com/adyen/checkout/payto/PayToComponentTest.kt
Labels: Chore

#1990 PayTo - Create configuration
  drop-in/api/drop-in.api
  drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/provider/ComponentProvider.kt
  payto/api/payto.api
  payto/src/main/java/com/adyen/checkout/payto/PayToConfiguration.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/provider/PayToComponentProvider.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/DefaultPayToDelegate.kt
  payto/src/test/java/com/adyen/checkout/payto/PayToConfigurationTest.kt
Labels: Chore

#1992 Move address lookup loading spinner
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/AddressLookupView.kt
  ui-core/src/main/res/layout/address_lookup_view.xml
  ui-core/src/main/res/values/styles.xml
Labels: Fix

#1991 Fix address lookup view state
  card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
  card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
  example-app/src/main/assets/lookup_options.json
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/AddressFormInput.kt
Labels: Fix

#1994 Downgrade AGP to 8.7.3
  gradle/libs.versions.toml
  gradle/verification-metadata.xml
Labels: Chore

#1996 Remove unnecessary Google Pay Compose Button dependency
  example-app/build.gradle
  gradle/libs.versions.toml
Labels: Chore

#1998 PayTo - Add PayToDelegate implementation
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/DefaultPayToDelegate.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/PayToDelegate.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/model/PayToInputData.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/model/PayToOutputData.kt
  payto/src/test/java/com/adyen/checkout/payto/internal/DefaultPayToDelegateTest.kt
Labels: Chore

#1993 Increase compile and target SDK to 35
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
  drop-in/src/main/res/anim/fade_out.xml
  drop-in/src/main/res/anim/slide_in_left_to_right.xml
  drop-in/src/main/res/anim/slide_in_right_to_left.xml
  drop-in/src/main/res/anim/slide_out_left_to_right.xml
  drop-in/src/main/res/anim/slide_out_right_to_left.xml
  example-app/src/main/java/com/adyen/checkout/example/extensions/WindowInsetsExtensions.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/blik/BlikActivity.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/CardActivity.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/giftcard/GiftCardActivity.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
  example-app/src/main/res/layout/activity_blik.xml
  example-app/src/main/res/layout/activity_card.xml
  example-app/src/main/res/layout/activity_gift_card.xml
  example-app/src/main/res/layout/activity_main.xml
  example-app/src/main/res/values/styles.xml
  example-app/src/main/res/values/styles_appbarlayout.xml
  example-app/src/main/res/values/styles_toolbar.xml
  gradle/libs.versions.toml
Labels: Feature

#1999 Fix Twint overriding store payment method mode
  twint/src/main/java/com/adyen/checkout/twint/internal/ui/DefaultTwintDelegate.kt
  twint/src/test/java/com/adyen/checkout/twint/internal/ui/DefaultTwintDelegateTest.kt
Labels: Fix

#2001 Emit specific exception when Google Pay is cancelled
  checkout-core/api/checkout-core.api
  checkout-core/src/main/java/com/adyen/checkout/core/exception/CancellationException.kt
  googlepay/api/googlepay.api
  googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayCancellationException.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegate.kt
  googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegateTest.kt
Labels: Fix

#2002 Update broken badge in readme
  README.md
Labels: Chore

#2003 Add version number to generated dependency updates table
  .github/release_notes_dependency_list.toml
  scripts/generate_release_notes.py
Labels: Chore

#2007 PayTo - Add PayId type adapter
  online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/ui/OnlineBankingView.kt
  online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/ui/model/OnlineBankingModel.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/DefaultPayToDelegate.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/PayToDelegate.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/model/PayIdType.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/model/PayIdTypeModel.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/model/PayToInputData.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/view/PayToView.kt
  payto/src/main/res/layout/payto_view.xml
  payto/src/main/res/values/strings.xml
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/LocalizedTextListAdapter.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/TextListAdapter.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/model/AddressListItem.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/AddressFormInput.kt
  ui-core/src/main/res/layout/text_item_view.xml
Labels: Chore

#2006 [Card scanning] Setup scanner
  card-scanning/api/card-scanning.api
  card-scanning/build.gradle
  card-scanning/src/main/java/com/adyen/checkout/card/scanning/AdyenCardScanner.kt
  card-scanning/src/main/java/com/adyen/checkout/card/scanning/AdyenCardScannerResult.kt
Labels: Chore

#2004 Fix address lookup formatting
  card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardView.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/model/AddressOutputData.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/AddressLookupOptionsAdapter.kt
  ui-core/src/test/java/com/adyen/checkout/ui/core/internal/ui/model/AddressOutputDataTest.kt
  ui-core/src/test/java/com/adyen/checkout/ui/core/internal/ui/view/LookupOptionTest.kt
Labels: Fix

#2011 Add gradle task to show dependency list
  .github/release_notes_dependency_list.toml
  build.gradle
  config/gradle/dependencyList.gradle
Labels: Chore

#2008 Show dependency changes in every PR
  .github/workflows/check_dependency_changes.yml
  .github/workflows/check_pr.yml
  scripts/check_dependency_changes.py
Labels: Chore

#2018 Add codeQL script
  .github/workflows/codeql.yml
Labels: Chore

#2020 Fix downloading gradle wrapper log leaking into dependency list task output
  scripts/check_dependency_changes.py
Labels: Chore

#2023 Fix address lookup options not showing in example app (card + sessions)
  example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardUiState.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardViewModel.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/card/compose/SessionsCardScreen.kt
Labels: Chore

#2024 Fix finalize_release workflow
  .github/workflows/finalize_release.yml
Labels: Chore

#2019 PayTo - Field validation
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/DefaultPayToDelegate.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/model/PayToOutputData.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/ui/view/PayToView.kt
  payto/src/main/java/com/adyen/checkout/payto/internal/util/PayToValidationUtils.kt
  payto/src/main/res/layout/payto_view.xml
  payto/src/main/res/values/strings.xml
  payto/src/main/res/values/styles.xml
  payto/src/test/java/com/adyen/checkout/payto/internal/util/PayToValidationUtilsTest.kt
Labels: Chore

#2022 Improve network logging
  checkout-core/src/main/java/com/adyen/checkout/core/internal/data/api/AdyenApiResponse.kt
  checkout-core/src/main/java/com/adyen/checkout/core/internal/data/api/HttpClient.kt
  checkout-core/src/main/java/com/adyen/checkout/core/internal/data/api/HttpClientExt.kt
  checkout-core/src/main/java/com/adyen/checkout/core/internal/data/api/OkHttpClient.kt
  components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsServiceTest.kt
Labels: Chore
