Repository Adyen/adyen-android, pull requests merged in 2025-01, with the labels that each got.

#1939 Release - Update PR description for release notes
  scripts/create_release_notes_pr.sh
Labels: Chore

#1936 Analytics - Track api errors
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
  3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
  ach/src/main/java/com/adyen/checkout/ach/internal/provider/ACHDirectDebitComponentProvider.kt
  ach/src/main/java/com/adyen/checkout/ach/internal/ui/DefaultACHDirectDebitDelegate.kt
  ach/src/test/java/com/adyen/checkout/ach/internal/ui/DefaultACHDirectDebitDelegateTest.kt
  bacs/src/main/java/com/adyen/checkout/bacs/internal/provider/BacsDirectDebitComponentProvider.kt
  bcmc/src/main/java/com/adyen/checkout/bcmc/internal/provider/BcmcComponentProvider.kt
  blik/src/main/java/com/adyen/checkout/blik/internal/provider/BlikComponentProvider.kt
  boleto/src/main/java/com/adyen/checkout/boleto/internal/provider/BoletoComponentProvider.kt
  card/src/main/java/com/adyen/checkout/card/internal/provider/CardComponentProvider.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
  card/src/main/java/com/adyen/checkout/card/internal/ui/StoredCardDelegate.kt
  card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
  card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
  cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/provider/CashAppPayComponentProvider.kt
  components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/ErrorEvent.kt
  drop-in/api/drop-in.api
  drop-in/src/main/java/com/adyen/checkout/dropin/SessionDropInService.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/service/BaseDropInServiceInterfaces.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInViewModel.kt
  drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/model/DropInActivityEvent.kt
  econtext/src/main/java/com/adyen/checkout/econtext/internal/provider/EContextComponentProvider.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/provider/GiftCardComponentProvider.kt
  giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegate.kt
  giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegateTest.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/internal/provider/GooglePayComponentProvider.kt
  ideal/src/main/java/com/adyen/checkout/ideal/internal/provider/IdealComponentProvider.kt
  instant/src/main/java/com/adyen/checkout/instant/internal/provider/InstantPaymentComponentProvider.kt
  issuer-list/src/main/java/com/adyen/checkout/issuerlist/internal/provider/IssuerListComponentProvider.kt
  mbway/src/main/java/com/adyen/checkout/mbway/internal/provider/MBWayComponentProvider.kt
  meal-voucher-fr/src/main/java/com/adyen/checkout/mealvoucherfr/internal/provider/MealVoucherFRComponentProvider.kt
  online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/provider/OnlineBankingComponentProvider.kt
  paybybank-us/src/main/java/com/adyen/checkout/paybybankus/internal/provider/PayByBankUSComponentProvider.kt
  paybybank/src/main/java/com/adyen/checkout/paybybank/internal/provider/PayByBankComponentProvider.kt
  redirect/src/main/java/com/adyen/checkout/redirect/internal/ui/DefaultRedirectDelegate.kt
  redirect/src/test/java/com/adyen/checkout/redirect/internal/ui/DefaultRedirectDelegateTest.kt
  sepa/src/main/java/com/adyen/checkout/sepa/internal/provider/SepaComponentProvider.kt
  sessions-core/build.gradle
  sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/SessionInteractor.kt
  sessions-core/src/test/java/com/adyen/checkout/sessions/core/internal/SessionInteractorTest.kt
  twint/src/main/java/com/adyen/checkout/twint/internal/provider/TwintComponentProvider.kt
  upi/src/main/java/com/adyen/checkout/upi/internal/provider/UPIComponentProvider.kt
Labels: Chore

#1953 Release - Clean up and remove develop mentions
  .github/ISSUE_TEMPLATE/ask_question.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/check_labels.yml
  .github/workflows/check_main.yml
  .github/workflows/check_pr.yml
  .github/workflows/check_release.yml
  .github/workflows/prepare_release.yml
  .github/workflows/run_ui_tests.yml
  README.md
Labels: Chore

#1954 Release - Add action to verify new dependencies
  .github/workflows/check_pr.yml
  .github/workflows/validate_dependencies.yml
  scripts/validate_dependencies_for_release_notes.py
Labels: Chore

#1957 Release - Add trigger finalize release workflow
  .github/workflows/fetch_version_name_from_release_notes.yml
  .github/workflows/trigger_finalize_release.yml
  scripts/fetch_release_notes_version_name.sh
  scripts/fetch_updated_release_notes_file.sh
Labels: Chore

#1955 Propagate additionalDetails on native 3ds2 cancel flow
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Cancelled3DS2Exception.kt
  3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
  3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
  RELEASE_NOTES.md
Labels: Feature

#1962 Prepare release 5.9.0
  README.md
  RELEASE_NOTES.md
  docs/payment-methods/GOOGLE_PAY.md
  example-app/build.gradle
  gradle/libs.versions.toml
Labels: Chore

#1966 Release process changes
  .github/.release_notes_allowed_labels_list
  .github/ISSUE_TEMPLATE/ask_question.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/release_notes_dependency_list.toml
  .github/workflows/check.yml
  .github/workflows/check_labels.yml
  .github/workflows/check_main.yml
  .github/workflows/check_pr.yml
  .github/workflows/check_release.yml
  .github/workflows/create_github_release.yml
  .github/workflows/create_release_notes_pr.yml
  .github/workflows/finalize_release.yml
  .github/workflows/generate_release_notes.yml
  .github/workflows/generate_version_name.yml
  .github/workflows/prepare_release.yml
  .github/workflows/publish_docs.yml
  .github/workflows/publish_release.yml
  .github/workflows/publish_to_maven_central.yml
  .github/workflows/run_ui_tests.yml
  .github/workflows/update_release_notes.yml
  .github/workflows/validate_dependencies.yml
  README.md
  RELEASE_NOTES.md
  build.gradle
  config/gradle/buildConfig.gradle
  config/gradle/release.gradle
  example-app/build.gradle
  gradle/libs.versions.toml
  scripts/check_release_notes_labels.sh
  scripts/create_release_notes_pr.sh
  scripts/generate_release_notes.py
  scripts/validate_dependencies_for_release_notes.py
  scripts/version_name.sh
Labels: Chore

#1969 Add SDK lifecycle section to readme
  README.md
Labels: Chore

#1970 V4 - Change OSSRH token
  .github/workflows/publish_release.yml
Labels: Chore

#1973 Address Lookup hide keyboard
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/AddressLookupView.kt
Labels: Fix

#1977 Address Lookup fix infinite loading
  example-app/src/main/java/com/adyen/checkout/example/repositories/AddressLookupRepository.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/AddressLookupDelegate.kt
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/DefaultAddressLookupDelegate.kt
Labels: Chore
