Repository Adyen/adyen-android, pull requests merged in 2025-06, with the labels that each got.

#2142 Add .kotlin folder to gitignore
  .gitignore
Labels: Chore

#2141 Accessibility - Expiry Date & Security Code
  card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardView.kt
  card/src/main/res/layout/card_brand_item.xml
  card/src/main/res/template/values/strings.xml.tt
  card/src/main/res/values-ar/strings.xml
  card/src/main/res/values-bg-rBG/strings.xml
  card/src/main/res/values-ca-rES/strings.xml
  card/src/main/res/values-cs-rCZ/strings.xml
  card/src/main/res/values-da-rDK/strings.xml
  card/src/main/res/values-de-rDE/strings.xml
  card/src/main/res/values-el-rGR/strings.xml
  card/src/main/res/values-es-rES/strings.xml
  card/src/main/res/values-et-rEE/strings.xml
  card/src/main/res/values-fi-rFI/strings.xml
  card/src/main/res/values-fr-rFR/strings.xml
  card/src/main/res/values-hr-rHR/strings.xml
  card/src/main/res/values-hu-rHU/strings.xml
  card/src/main/res/values-is-rIS/strings.xml
  card/src/main/res/values-it-rIT/strings.xml
  card/src/main/res/values-ja-rJP/strings.xml
  card/src/main/res/values-ko-rKR/strings.xml
  card/src/main/res/values-lt-rLT/strings.xml
  card/src/main/res/values-lv-rLV/strings.xml
  card/src/main/res/values-nb-rNO/strings.xml
  card/src/main/res/values-nl-rNL/strings.xml
  card/src/main/res/values-pl-rPL/strings.xml
  card/src/main/res/values-pt-rBR/strings.xml
  card/src/main/res/values-pt-rPT/strings.xml
  card/src/main/res/values-ro-rRO/strings.xml
  card/src/main/res/values-ru-rRU/strings.xml
  card/src/main/res/values-sk-rSK/strings.xml
  card/src/main/res/values-sl-rSI/strings.xml
  card/src/main/res/values-sv-rSE/strings.xml
  card/src/main/res/values-zh-rCN/strings.xml
  card/src/main/res/values-zh-rTW/strings.xml
  card/src/main/res/values/strings.xml
  ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/ViewExtensions.kt
Labels: Feature

#2149 Add bottom margin to card brand selection section
  card/src/main/res/layout/card_view.xml
Labels: Fix

#2151 v6 - Add analytics to core module
  core/api/core.api
  core/build.gradle
  core/src/main/java/com/adyen/checkout/core/AnalyticsConfiguration.kt
  core/src/main/java/com/adyen/checkout/core/CheckoutConfiguration.kt
  core/src/main/java/com/adyen/checkout/core/internal/BaseConfigurationBuilder.kt
  core/src/main/java/com/adyen/checkout/core/internal/Configuration.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/AnalyticsEvent.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/AnalyticsManager.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/AnalyticsManagerFactory.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/AnalyticsPlatform.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/AnalyticsPlatformParams.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/AnalyticsSource.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/CheckoutAttemptIdState.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/DefaultAnalyticsManager.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/DirectAnalyticsEventCreation.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/ErrorEvent.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/GenericEvents.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/data/AnalyticsRepository.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/data/DefaultAnalyticsRepository.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/data/local/AnalyticsLocalDataStore.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/data/local/ErrorAnalyticsLocalDataStore.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/data/local/InfoAnalyticsLocalDataStore.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/data/local/LogAnalyticsLocalDataStore.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/data/remote/AnalyticsRemoteDataStore.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/data/remote/AnalyticsSetupProvider.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/data/remote/AnalyticsTrackRequestProvider.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/data/remote/DefaultAnalyticsRemoteDataStore.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/data/remote/DefaultAnalyticsSetupProvider.kt
  core/src/main/java/com/adyen/checkout/core/internal/data/api/AnalyticsService.kt
  core/src/main/java/com/adyen/checkout/core/internal/data/model/AnalyticsSetupRequest.kt
  core/src/main/java/com/adyen/checkout/core/internal/data/model/AnalyticsSetupResponse.kt
  core/src/main/java/com/adyen/checkout/core/internal/data/model/AnalyticsTrackError.kt
  core/src/main/java/com/adyen/checkout/core/internal/data/model/AnalyticsTrackInfo.kt
  core/src/main/java/com/adyen/checkout/core/internal/data/model/AnalyticsTrackLog.kt
  core/src/main/java/com/adyen/checkout/core/internal/data/model/AnalyticsTrackRequest.kt
  core/src/main/java/com/adyen/checkout/core/internal/data/model/EmptyResponse.kt
  core/src/main/java/com/adyen/checkout/core/internal/data/model/JsonUtils.kt
  core/src/main/java/com/adyen/checkout/core/internal/ui/model/AnalyticsParams.kt
  core/src/main/java/com/adyen/checkout/core/internal/ui/model/CommonComponentParams.kt
  core/src/main/java/com/adyen/checkout/core/internal/ui/model/CommonComponentParamsMapper.kt
  core/src/main/java/com/adyen/checkout/core/internal/ui/model/ComponentParams.kt
  core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/MBWayConfiguration.kt
  core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/MBWayDelegate.kt
  core/src/test/java/core/adyen/checkout/core/internal/analytics/AnalyticsPlatformParamsTest.kt
  core/src/test/java/core/adyen/checkout/core/internal/analytics/DefaultAnalyticsManagerTest.kt
  core/src/test/java/core/adyen/checkout/core/internal/analytics/data/DefaultAnalyticsRepositoryTest.kt
  core/src/test/java/core/adyen/checkout/core/internal/analytics/data/remote/AnalyticsTrackRequestProviderTest.kt
  core/src/test/java/core/adyen/checkout/core/internal/analytics/data/remote/DefaultAnalyticsSetupProviderTest.kt
  core/src/test/java/core/adyen/checkout/core/internal/data/api/AnalyticsServiceTest.kt
  core/src/test/java/core/adyen/checkout/core/internal/data/model/AnalyticsSetupRequestTest.kt
  core/src/test/java/core/adyen/checkout/core/internal/data/model/AnalyticsSetupResponseTest.kt
  core/src/test/java/core/adyen/checkout/core/internal/data/model/AnalyticsTrackInfoTest.kt
  core/src/test/java/core/adyen/checkout/core/internal/data/model/AnalyticsTrackLogTest.kt
  core/src/test/java/core/adyen/checkout/core/internal/data/model/AnalyticsTrackRequestTest.kt
  core/src/testFixtures/java/com/adyen/checkout/test/LoggingExtension.kt
  core/src/testFixtures/java/com/adyen/checkout/test/TestDispatcherExtension.kt
Labels: Chore

#2154 Sonatype - Migrate workflows to Sonatype Central portal
  .github/workflows/publish_to_maven_central.yml
  config/gradle/release.gradle
  scripts/drop_all_open_ossrh_repositories.py
  scripts/move_ossrh_repository_to_central_portal.py
Labels: Chore

#2157 Add checkoutOption configuration to Google Pay
  example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
  googlepay/api/googlepay.api
  googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayConfiguration.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParams.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParamsMapper.kt
  googlepay/src/main/java/com/adyen/checkout/googlepay/internal/util/GooglePayUtils.kt
  googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParamsMapperTest.kt
  googlepay/src/test/java/com/adyen/checkout/googlepay/internal/util/GooglePayUtilsTest.kt
Labels: Feature

#2156 v6 - Pass component params to PaymentFacilitator
  core/src/main/java/com/adyen/checkout/core/internal/AdvancedPaymentFacilitatorFactory.kt
  core/src/main/java/com/adyen/checkout/core/internal/PaymentFacilitator.kt
  core/src/main/java/com/adyen/checkout/core/internal/SessionsPaymentFacilitatorFactory.kt
Labels: Chore

#2165 Convert MBWay UI
  core/api/core.api
  core/src/main/java/com/adyen/checkout/core/AdyenPaymentFlow.kt
  core/src/main/java/com/adyen/checkout/core/internal/ui/view/PayButton.kt
  core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/view/MbWayComponent.kt
  example-app/src/main/java/com/adyen/checkout/example/ui/v6/V6Activity.kt
  ui/api/ui.api
  ui/src/main/java/com/adyen/checkout/ui/internal/AdyenTextField.kt
  ui/src/main/java/com/adyen/checkout/ui/internal/AdyenTextFieldDecorationBox.kt
Labels: Chore

#2162 v6 - Add PaymentMethodProvider
  core/src/main/java/com/adyen/checkout/core/AdyenPaymentFlow.kt
  core/src/main/java/com/adyen/checkout/core/internal/AdvancedComponentEventHandler.kt
  core/src/main/java/com/adyen/checkout/core/internal/AdvancedPaymentFacilitatorFactory.kt
  core/src/main/java/com/adyen/checkout/core/internal/AdyenComponent.kt
  core/src/main/java/com/adyen/checkout/core/internal/BaseComponentState.kt
  core/src/main/java/com/adyen/checkout/core/internal/PaymentComponentEvent.kt
  core/src/main/java/com/adyen/checkout/core/internal/PaymentFacilitator.kt
  core/src/main/java/com/adyen/checkout/core/internal/PaymentFacilitatorFactory.kt
  core/src/main/java/com/adyen/checkout/core/internal/PaymentFacilitatorProvider.kt
  core/src/main/java/com/adyen/checkout/core/internal/PaymentMethodFactory.kt
  core/src/main/java/com/adyen/checkout/core/internal/PaymentMethodProvider.kt
  core/src/main/java/com/adyen/checkout/core/internal/SessionsPaymentFacilitatorFactory.kt
  core/src/main/java/com/adyen/checkout/core/internal/ui/EventDelegate.kt
  core/src/main/java/com/adyen/checkout/core/internal/ui/PaymentDelegate.kt
  core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/MBWayFactory.kt
Labels: Chore

#2159 V6 - MBWay - Generate componentState from delegate state
  core/api/core.api
  core/src/main/java/com/adyen/checkout/core/internal/analytics/AnalyticsManagerFactory.kt
  core/src/main/java/com/adyen/checkout/core/internal/analytics/data/remote/DefaultAnalyticsSetupProvider.kt
  core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/MBWayComponentState.kt
  core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/MBWayDelegate.kt
  core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/MBWayFactory.kt
  core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/model/MBWayStateUpdaterRegistry.kt
  core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/model/MBWayValidatorRegistry.kt
  core/src/main/java/com/adyen/checkout/core/paymentmethod/PaymentComponentState.kt
  core/src/test/java/com/adyen/checkout/core/internal/analytics/TestAnalyticsManager.kt
Labels: Chore

#2167 Sonatype - Central Portal migration
  .github/workflows/publish_to_maven_central.yml
  .gitignore
  config/gradle/release.gradle
  scripts/drop_all_open_ossrh_repositories.py
  settings.gradle
Labels: Chore

#2172 v6 - MBWay country code picker
  core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/view/MbWayComponent.kt
  gradle/verification-metadata.xml
  ui/build.gradle
  ui/src/main/java/com/adyen/checkout/ui/internal/FullScreenDialog.kt
Labels: Chore

#2177 V6 - Sonatype - Central Portal migration
  .github/workflows/publish_to_maven_central.yml
  .gitignore
  config/gradle/release.gradle
  scripts/drop_all_open_ossrh_repositories.py
  settings.gradle
Labels: Chore
